package com.curverto.app

object SupportedCurrencies {
    val currencies = mapOf(
        "USD" to "United States",
        "EUR" to "Euro",
        "GBP" to "British Pound",
        "AUD" to "Australian Dollar",
        "CAD" to "Canadian Dollar",
        "CHF" to "Switzerland Franc",
        "AED" to "United Arab Emirates Dirham",
        "BHD" to "Bahraini Dinar",
        "CNY" to "Chinese Yuan",
        "TRY" to "Turkish Lira",
        "EGP" to "Egyptian Pound",
        "KWD" to "Kuwaiti Dinar",
        "JPY" to "Japanese Yen",
        "QAR" to "Qatari Rial",
        "THB" to "Thai Baht",
        "BGN" to "Bulgarian Lev",
        "CLP" to "Chilean Peso",
        "CZK" to "Czech Koruna",
        "DKK" to "Danish Krone",
        "GEL" to "Georgian Lari",
        "ALL" to "Albanian Lek",
        "AFN" to "Afghan Afghani",
        "AMD" to "Armenian Dram",
        "AOA" to "Angolan Kwanza",
        "ARS" to "Argentine Peso",
        "AWG" to "Aruban Florin",
        "AZN" to "Azerbaijani Manat",
        "BAM" to "Bosnia and Herzegovina Convertible Mark",
        "BBD" to "Barbadian Dollar",
        "BDT" to "Bangladeshi Taka",
        "BIF" to "Burundian Franc",
        "BND" to "Brunei Dollar",
        "BOB" to "Bolivian Boliviano",
        "BRL" to "Brazilian Real",
        "BWP" to "Botswanan Pula",
        "BYN" to "Belarusian Ruble",
        "CDF" to "Congolese Franc",
        "COP" to "Colombian Peso",
        "NOK" to "Norwegian Krone",
        "PLN" to "Polish Zloty",
        "SEK" to "Swedish Krona",
        "CUP" to "Cuban Peso",
        "DJF" to "Djiboutian Franc",
        "DOP" to "Dominican Peso",
        "DZD" to "Algerian Dinar",
        "ERN" to "Eritrean Nakfa",
        "ETB" to "Ethiopian Birr",
        "GHS" to "Ghanaian Cedi",
        "GIP" to "Gibraltar Pound",
        "GMD" to "Gambian Dalasi",
        "GNF" to "Guinean Franc",
        "HKD" to "Hong Kong Dollar",
        "HNL" to "Honduran Lempira",
        "HRK" to "Croatian Kuna",
        "HUF" to "Hungarian Forint",
        "IDR" to "Indonesian Rupiah",
        "INR" to "Indian Rupee",
        "IQD" to "Iraqi Dinar",
        "IRR" to "Iranian Rial",
        "ISK" to "Icelandic Króna",
        "JMD" to "Jamaican Dollar",
        "JOD" to "Jordanian Dinar",
        "KES" to "Kenyan Shilling",
        "KGS" to "Kyrgystani Som",
        "KHR" to "Cambodian Riel",
        "KZT" to "Kazakhstani Tenge",
        "LAK" to "Laotian Kip",
        "LBP" to "Lebanese Pound",
        "LKR" to "Sri Lankan Rupee",
        "LRD" to "Liberian Dollar",
        "MAD" to "Moroccan Dirham",
        "MDL" to "Moldovan Leu",
        "MUR" to "Mauritian Rupee",
        "MVR" to "Maldivian Rufiyaa",
        "MWK" to "Malawian Kwacha",
        "MXN" to "Mexican Peso",
        "MYR" to "Malaysian Ringgit",
        "MZN" to "Mozambican Metical",
        "NGN" to "Nigerian Naira",
        "NPR" to "Nepalese Rupee",
        "NZD" to "New Zealand Dollar",
        "OMR" to "Omani Rial",
        "PAB" to "Panamanian Balboa",
        "PEN" to "Peruvian Nuevo Sol",
        "PHP" to "Philippine Peso",
        "PKR" to "Pakistani Rupee",
        "RON" to "Romanian Leu",
        "RSD" to "Serbian Dinar",
        "RUB" to "Russian Ruble",
        "RWF" to "Rwandan Franc",
        "SAR" to "Saudi Riyal",
        "SCR" to "Seychellois Rupee",
        "SDG" to "Sudanese Pound",
        "SGD" to "Singapore Dollar",
        "SLE" to "Sierra Leonean Leone",
        "SOS" to "Somali Shilling",
        "TJS" to "Tajikistani Somoni",
        "TMT" to "Turkmenistan Manat",
        "TND" to "Tunisian Dinar",
        "TWD" to "New Taiwan Dollar",
        "TZS" to "Tanzanian Shilling",
        "UAH" to "Ukrainian Hryvnia",
        "UGX" to "Ugandan Shilling",
        "UYU" to "Uruguayan Peso",
        "UZS" to "Uzbekistani Som",
        "VES" to "Venezuelan Bolívar",
        "VND" to "Vietnamese Dong",
        "YER" to "Yemeni Rial",
        "ZAR" to "South African Rand",
        "ZMW" to "Zambian Kwacha",
        "ZWL" to "Zimbabwean Dollar"
    )



}